# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(300, 200)
        LoginDialog.setStyleSheet("QDialog { background-color: black; color: white; }")

        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setObjectName("verticalLayout")

        self.user_label = QtWidgets.QLabel(LoginDialog)
        self.user_label.setStyleSheet("color: white;")
        self.user_label.setObjectName("user_label")

        self.verticalLayout.addWidget(self.user_label)

        self.user_entry = QtWidgets.QLineEdit(LoginDialog)
        self.user_entry.setStyleSheet("background-color: black; color: white;")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_entry.sizePolicy().hasHeightForWidth())
        self.user_entry.setSizePolicy(sizePolicy)
        self.user_entry.setObjectName("user_entry")
        self.verticalLayout.addWidget(self.user_entry)
        self.password_label = QtWidgets.QLabel(LoginDialog)
        self.password_label.setStyleSheet("color: white;")
        self.password_label.setObjectName("password_label")
        self.verticalLayout.addWidget(self.password_label)
        self.password_entry = QtWidgets.QLineEdit(LoginDialog)
        self.password_entry.setStyleSheet("background-color: black; color: white;")
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_entry.sizePolicy().hasHeightForWidth())
        self.password_entry.setSizePolicy(sizePolicy)
        self.password_entry.setObjectName("password_entry")
        self.verticalLayout.addWidget(self.password_entry)

        self.login_button = QtWidgets.QPushButton(LoginDialog)
        self.login_button.setStyleSheet("background-color: green; color: white;")
        self.login_button.setMinimumSize(QtCore.QSize(200, 50))
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login"))
        self.user_label.setText(_translate("LoginDialog", "Usuário:"))
        self.password_label.setText(_translate("LoginDialog", "Senha:"))
        self.login_button.setText(_translate("LoginDialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec_())
