# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(594, 359)
        LoginDialog.setStyleSheet("QDialog { background-color: black; color: white; }")
        self.user_label = QtWidgets.QLabel(LoginDialog)
        self.user_label.setGeometry(QtCore.QRect(270, 80, 51, 16))
        self.user_label.setStyleSheet("color: white;")
        self.user_label.setObjectName("user_label")
        self.user_entry = QtWidgets.QLineEdit(LoginDialog)
        self.user_entry.setGeometry(QtCore.QRect(270, 110, 261, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_entry.sizePolicy().hasHeightForWidth())
        self.user_entry.setSizePolicy(sizePolicy)
        self.user_entry.setStyleSheet("color: black; text-transform: uppercase; font-weight: bold;\n"
"border-radius: 10px")
        self.user_entry.setObjectName("user_entry")
        self.password_label = QtWidgets.QLabel(LoginDialog)
        self.password_label.setGeometry(QtCore.QRect(270, 160, 51, 16))
        self.password_label.setStyleSheet("color: white; ")
        self.password_label.setObjectName("password_label")
        self.password_entry = QtWidgets.QLineEdit(LoginDialog)
        self.password_entry.setGeometry(QtCore.QRect(270, 190, 261, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_entry.sizePolicy().hasHeightForWidth())
        self.password_entry.setSizePolicy(sizePolicy)
        self.password_entry.setStyleSheet("color: black;\n""border-radius: 10px")
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_entry.setObjectName("password_entry")
        self.login_button = QtWidgets.QPushButton(LoginDialog)
        self.login_button.setGeometry(QtCore.QRect(300, 240, 201, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("""
             #login_button {
                            background-color: rgb(0, 0, 255);
                            border-radius: 5px;
                            color: white;
                          }
             #login_button:hover {
                             background-color: aqua;
                                        color: blue;
                                        }
             #login_button:pressed {
                             background-color: teal;
                                        color: blue;
                                        }                           

""")

        self.login_button.setObjectName("login_button")
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setGeometry(QtCore.QRect(0, 60, 261, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("src/img/SQLToolsLogin.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(520, 320, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.user_label.raise_()
        self.user_entry.raise_()
        self.password_label.raise_()
        self.password_entry.raise_()
        self.login_button.raise_()
        self.label_2.raise_()

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login"))
        self.user_label.setText(_translate("LoginDialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Usuário:</span></p></body></html>"))
        self.password_label.setText(_translate("LoginDialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Senha:</span></p></body></html>"))
        self.login_button.setText(_translate("LoginDialog", "Login"))
        self.label_2.setText(_translate("LoginDialog", "<html><head/><body><p><span style=\" color:#ffffff;\">Versão 3.0</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec_())
